### ISSUE TITLE
"Complete" or Large summarization 

### ISSUE THREAD

**Issue by DeLuca92** [pszemraj/textsum#16]
Hello,

1- Can I use this repo for portuguese texts?
2- I have a large conversation and Can I make a complete or good summarization for this  conversation?

Where I change to Portuguese?

**Comment by pszemraj** [comment]
Hi, thanks for reaching out. there's some good news and bad news for 1):

- good news: you can use this repo for portuguese, it should work fine 
- bad news: the default model in this repo is english only, so you'd need to find/pass in a multilingual model (preferably one fine-tuned to understand/summarize pt) when creating your summarizer, like a fine-tune of [mlong-t5](https://huggingface.co/agemagician/mlong-t5-tglobal-base). 

An example of how to load a [different model](https://huggingface.co/Joemgu/mlong-t5-large-sumstew) (note: this is **not** tuned on portuguese but might be better than an english-only model)

```python
from textsum.summarize import Summarizer

summarizer = Summarizer(model_name_or_path = "Joemgu/mlong-t5-large-sumstew")
# run inference as shown in readme and/or wiki
```

for question 2, long conversations etc should be handled fine, as long as you have the hardware to run the model. you can try increasing the `token_batch_length` from the default of 4096 up to 16384 when you load the model:

```python
from textsum.summarize import Summarizer

summarizer = Summarizer(
    model_name_or_path="Joemgu/mlong-t5-large-sumstew", token_batch_length=12288
)
# run inference as shown in readme and/or wiki
```

**Comment by pszemraj** [comment]
going to close this for now, lmk if you have further questions!
