### ISSUE TITLE
txtsum web UI error (+ fix)

### ISSUE THREAD

**Issue by LoopControl** [pszemraj/textsum#9]
Just installed with `pip install txtsum` then `pip install txtsum[ui]` for the web UI.

When running `textsum-ui`, it errors out with:

```
    from .pytorch import *  # type: ignore[misc]
  File "/home/user/apps/anaconda3/envs/autogptq/lib/python3.10/site-packages/doctr/models/recognition/predictor/pytorch.py", line 14, in <module>
    from ._utils import remap_preds, split_crops
  File "/home/user/apps/anaconda3/envs/autogptq/lib/python3.10/site-packages/doctr/models/recognition/predictor/_utils.py", line 10, in <module>
    from ..utils import merge_multi_strings
  File "/home/user/apps/anaconda3/envs/autogptq/lib/python3.10/site-packages/doctr/models/recognition/utils.py", line 8, in <module>
    from rapidfuzz.string_metric import levenshtein
ModuleNotFoundError: No module named 'rapidfuzz.string_metric'
```

Some googling led to this: https://github.com/mindee/doctr/issues/1186 where apparently the doctr module had a breaking change.

Ran the workaround mentioned and txtsum-ui seems to work now:

`pip install rapidfuzz==2.15.1`

**Comment by pszemraj** [comment]
Hi! Thanks for raising this (and the solution)! I had noticed this with the (_for now_) API-independent [document summarization](https://huggingface.co/spaces/pszemraj/document-summarization) demo I have on hf, but forgot to include the specific req in `textsum`
- As an aside, if your main use case is a demo app or UI, check out the Colab linked there, as it's an early version/preview of what will eventually be added to the package :)

I will make sure to include the dependency fix with #8, which should be ready to merge in the next few days, just need to run some tests
